export const FETCH_COLLECTOR_DATA = 'FETCH_COLLECTOR_DATA';
export const FETCH_COLLECTOR_DATA_RESPONSE = 'FETCH_COLLECTOR_DATA_RESPONSE';
export const FETCH_ENCOUNTERS_FOR_TIMELINE_DETAILS = 'FETCH_ENCOUNTERS_FOR_TIMELINE_DETAILS';
export const FETCH_ENCOUNTERS_FOR_TIMELINE_DETAILS_RESPONSE = 'FETCH_ENCOUNTERS_FOR_TIMELINE_DETAILS_RESPONSE';