export const FETCH_COLLECTOR_DATA = 'FETCH_COLLECTOR_DATA';
export const FETCH_COLLECTOR_DATA_RESPONSE = 'FETCH_COLLECTOR_DATA_RESPONSE';

export const FETCH_ENCOUNTERS_FOR_TIMELINE_DETAILS = 'FETCH_ENCOUNTERS_FOR_TIMELINE_DETAILS';
export const FETCH_ENCOUNTERS_FOR_TIMELINE_DETAILS_RESPONSE = 'FETCH_ENCOUNTERS_FOR_TIMELINE_DETAILS_RESPONSE';

export const FETCH_ENCOUNTERS_FOR_PLAYER_IN_COLLECTOR = 'FETCH_ENCOUNTERS_FOR_PLAYER_IN_COLLECTOR';
export const FETCH_ENCOUNTERS_FOR_PLAYER_IN_COLLECTOR_RESPONSE = 'FETCH_ENCOUNTERS_FOR_PLAYER_IN_COLLECTOR_RESPONSE';
export const APPLY_PROFESSION_FILTER = 'APPLY_PROFESSION_FILTER';
export const APPLY_ROLE_FILTER = 'APPLY_ROLE_FILTER';
export const RESET_PROFESSION_AND_ROLE_FILTERS = 'RESET_PROFESSION_AND_ROLE_FILTERS';

export const FETCH_USER_BY_SESSION_TOKEN = 'FETCH_USER_BY_SESSION_TOKEN';
export const FETCH_USER_BY_SESSION_TOKEN_RESPONSE = 'FETCH_USER_BY_SESSION_TOKEN_RESPONSE';
export const VERIFY_API_KEY = 'VERIFY_API_KEY';
export const VERIFY_API_KEY_RESPONSE = 'VERIFY_API_KEY_RESPONSE';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_OUT = 'SIGN_OUT';
export const RESET_LOGIN_SIGNUP = 'RESET_LOGIN_SIGNUP';

export const FETCH_ENCOUNTERS_BY_ACCOUNT_NAME = 'FETCH_ENCOUNTERS_BY_ACCOUNT_NAME';
export const FETCH_ENCOUNTERS_BY_ACCOUNT_NAME_RESPONSE = 'FETCH_ENCOUNTERS_BY_ACCOUNT_NAME_RESPONSE';
export const CLEAR_ENCOUNTERS_LIST = 'CLEAR_ENCOUNTERS_LIST';