export const FETCH_COLLECTOR_DATA = 'FETCH_COLLECTOR_DATA';
export const FETCH_COLLECTOR_DATA_RESPONSE = 'FETCH_COLLECTOR_DATA_RESPONSE';

export const FETCH_ENCOUNTERS_FOR_TIMELINE_DETAILS = 'FETCH_ENCOUNTERS_FOR_TIMELINE_DETAILS';
export const FETCH_ENCOUNTERS_FOR_TIMELINE_DETAILS_RESPONSE = 'FETCH_ENCOUNTERS_FOR_TIMELINE_DETAILS_RESPONSE';

export const FETCH_ENCOUNTERS_FOR_PLAYER_IN_COLLECTOR = 'FETCH_ENCOUNTERS_FOR_PLAYER_IN_COLLECTOR';
export const FETCH_ENCOUNTERS_FOR_PLAYER_IN_COLLECTOR_RESPONSE = 'FETCH_ENCOUNTERS_FOR_PLAYER_IN_COLLECTOR_RESPONSE';
export const APPLY_PROFESSION_FILTER = 'APPLY_PROFESSION_FILTER';
export const APPLY_ROLE_FILTER = 'APPLY_ROLE_FILTER';
export const RESET_PROFESSION_AND_ROLE_FILTERS = 'RESET_PROFESSION_AND_ROLE_FILTERS';
